language: node_js
node_js:
  - "8"
sudo: required
dist: trusty
addons:
  chrome: stable
before_install:
  - sudo apt-get update
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - google-chrome-stable --version
  - gulp testSpecs && gulp testVisual --applitools.pageLoadDelay=3 --browserLogs=false
